"""market state

Revision ID: ccea5bcd85df
Revises: 922ddccd69fd
Create Date: 2026-09-30 07:11:02.391396

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccea5bcd85df"
down_revision: str | Sequence[str] | None = "922ddccd69fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_state",
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("console", "pc", name="platform", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.Column("listings_csv", sa.String(length=120), nullable=False),
        sa.Column("range_min", sa.Integer(), nullable=True),
        sa.Column("range_max", sa.Integer(), nullable=True),
        sa.Column("extinct_since", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_market_state_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("player_id", "platform", name=op.f("pk_market_state")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("market_state")
    # ### end Alembic commands ###
