"""source status

Revision ID: 922ddccd69fd
Revises: 9b9b4830cb58
Create Date: 2026-09-29 22:03:48.438546

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "922ddccd69fd"
down_revision: str | Sequence[str] | None = "9b9b4830cb58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_status",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("paused_until", sa.DateTime(), nullable=True),
        sa.Column("pause_reason", sa.String(length=500), nullable=True),
        sa.Column("last_success_at", sa.DateTime(), nullable=True),
        sa.Column("last_error_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("source", name=op.f("pk_source_status")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("source_status")
    # ### end Alembic commands ###
