"""leak inbox and pool

Revision ID: daee37e882b4
Revises: 54c0a819794c
Create Date: 2026-09-30 20:24:51.119956

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "daee37e882b4"
down_revision: str | Sequence[str] | None = "54c0a819794c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leak_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("guid", sa.String(length=300), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("is_leak", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("promo_id", sa.Integer(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["promo_id"],
            ["promos.id"],
            name=op.f("fk_leak_items_promo_id_promos"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leak_items")),
        sa.UniqueConstraint("source", "guid", name="uq_leak_items_source_guid"),
    )
    with op.batch_alter_table("leak_items", schema=None) as batch_op:
        batch_op.create_index("ix_leak_items_published_at", ["published_at"], unique=False)

    op.create_table(
        "pool_cards",
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("promo_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.Column("until", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_pool_cards_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["promo_id"],
            ["promos.id"],
            name=op.f("fk_pool_cards_promo_id_promos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("player_id", name=op.f("pk_pool_cards")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pool_cards")
    with op.batch_alter_table("leak_items", schema=None) as batch_op:
        batch_op.drop_index("ix_leak_items_published_at")

    op.drop_table("leak_items")
    # ### end Alembic commands ###
