"""player usage data

Revision ID: 4634b02314e2
Revises: c44fd8f05191
Create Date: 2026-09-30 12:05:51.287850

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4634b02314e2"
down_revision: str | Sequence[str] | None = "c44fd8f05191"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chem_style", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("games_used", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("goals_per_game", sa.Double(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_column("goals_per_game")
        batch_op.drop_column("games_used")
        batch_op.drop_column("chem_style")

    # ### end Alembic commands ###
