"""community chem styles

Revision ID: e87bc3f0e7c3
Revises: 4634b02314e2
Create Date: 2026-09-30 12:24:30.841844

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e87bc3f0e7c3"
down_revision: str | Sequence[str] | None = "4634b02314e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chem_styles", sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_column("chem_styles")

    # ### end Alembic commands ###
