"""initial schema

Revision ID: c9c48dc386f7
Revises:
Create Date: 2026-09-29 20:05:42.418246

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9c48dc386f7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ea_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("position", sa.String(length=8), nullable=True),
        sa.Column("card_type", sa.String(length=50), nullable=True),
        sa.Column("league", sa.String(length=100), nullable=True),
        sa.Column("nation", sa.String(length=100), nullable=True),
        sa.Column("club", sa.String(length=100), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
        sa.UniqueConstraint("ea_id", name=op.f("uq_players_ea_id")),
    )
    op.create_table(
        "promos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("confidence", sa.Double(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_promos_confidence_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promos")),
    )
    op.create_table(
        "alerts_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule", sa.String(length=32), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_alerts_log_player_id_players"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts_log")),
    )
    with op.batch_alter_table("alerts_log", schema=None) as batch_op:
        batch_op.create_index(
            "ix_alerts_log_rule_player_id_sent_at", ["rule", "player_id", "sent_at"], unique=False
        )

    op.create_table(
        "portfolio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("buy_price", sa.Integer(), nullable=False),
        sa.Column("bought_at", sa.DateTime(), nullable=False),
        sa.Column("sell_price", sa.Integer(), nullable=True),
        sa.Column("sold_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "holding", "listed", "sold", name="positionstatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.CheckConstraint("buy_price > 0", name=op.f("ck_portfolio_buy_price_positive")),
        sa.CheckConstraint(
            "sell_price IS NULL OR sell_price > 0", name=op.f("ck_portfolio_sell_price_positive")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_portfolio_player_id_players"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio")),
    )
    op.create_table(
        "price_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("console", "pc", name="platform", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("price > 0", name=op.f("ck_price_snapshots_price_positive")),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_price_snapshots_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_snapshots")),
    )
    with op.batch_alter_table("price_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_price_snapshots_player_id_captured_at", ["player_id", "captured_at"], unique=False
        )

    op.create_table(
        "promo_links",
        sa.Column("promo_id", sa.Integer(), nullable=False),
        sa.Column(
            "link_type",
            sa.Enum(
                "player", "league", "nation", "club", name="linktype", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("link_value", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["promo_id"],
            ["promos.id"],
            name=op.f("fk_promo_links_promo_id_promos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("promo_id", "link_type", "link_value", name=op.f("pk_promo_links")),
    )
    op.create_table(
        "watchlist",
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("target_buy", sa.Integer(), nullable=True),
        sa.Column("target_sell", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "target_buy IS NULL OR target_buy > 0", name=op.f("ck_watchlist_target_buy_positive")
        ),
        sa.CheckConstraint(
            "target_sell IS NULL OR target_sell > 0", name=op.f("ck_watchlist_target_sell_positive")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_watchlist_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("player_id", name=op.f("pk_watchlist")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("watchlist")
    op.drop_table("promo_links")
    with op.batch_alter_table("price_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_price_snapshots_player_id_captured_at")

    op.drop_table("price_snapshots")
    op.drop_table("portfolio")
    with op.batch_alter_table("alerts_log", schema=None) as batch_op:
        batch_op.drop_index("ix_alerts_log_rule_player_id_sent_at")

    op.drop_table("alerts_log")
    op.drop_table("promos")
    op.drop_table("players")
    # ### end Alembic commands ###
