"""card pairs

Revision ID: fa11c2698fed
Revises: daee37e882b4
Create Date: 2026-09-30 20:40:13.139229

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa11c2698fed"
down_revision: str | Sequence[str] | None = "daee37e882b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_pairs",
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("holo_player_id", sa.Integer(), nullable=True),
        sa.Column("checked_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["holo_player_id"],
            ["players.id"],
            name=op.f("fk_card_pairs_holo_player_id_players"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_card_pairs_player_id_players"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("player_id", name=op.f("pk_card_pairs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("card_pairs")
    # ### end Alembic commands ###
